version: "3"
services:
  ca:
    build: .
    image: meiji-nifty:latest
    command: bash -c "cd /source/src && ./keygen && ./data_enc"
    volumes:
      - auxdata:/source/src/auxdata
      - encdata:/source/src/encdata
      - settings:/source/src/settings
    networks:
      - localnet
  client:
    build: .
    image: meiji-nifty:latest
    command: bash -c "cd /source/src && ./client server 10200"
    volumes:
      - settings:/source/src/settings
    networks:
      - localnet
    depends_on:
      - ca
  server:
    build: .
    image: meiji-nifty:latest
    command: bash -c "cd /source/src && ./server 10200"
    volumes:
      - auxdata:/source/src/auxdata
      - encdata:/source/src/encdata
      - settings:/source/src/settings
    networks:
      - localnet
    depends_on:
      - ca

volumes:
  auxdata:
  encdata:
  settings:

networks:
  localnet:
