version: "3"
services:
  base_image:
    build: .
    image: meiji-nifty:latest
  ca:
    image: meiji-nifty:latest
    command: /source/scripts/initialize.sh /source
    volumes:
      - auxdata:/source/auxdata
      - encdata:/source/encdata
      - settings:/source/settings
    networks:
      - localnet
    depends_on:
      - base_image
  client:
    image: meiji-nifty:latest
    command: bash -c "cd /source/src && ./client server 80"
    volumes:
      - settings:/source/settings
    networks:
      - localnet
    depends_on:
      - ca
      - base_image
  server:
    image: meiji-nifty:latest
    command: bash -c "cd /source/src && ./server 80"
    volumes:
      - auxdata:/source/auxdata
      - encdata:/source/encdata
      - settings:/source/settings
    networks:
      - localnet
    depends_on:
      - ca
      - base_image

volumes:
  auxdata:
  encdata:
  settings:

networks:
  localnet:
    driver: bridge
